---
title: "Example 1"
output:
  md_document:
    variant: markdown_github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(lazyeval)
library(knitr)
library(testthat)
df <- readr::read_csv("sample_data_1.csv")
```

## Dplyr example 1

We have data that looks like this:

```{r}
knitr::kable(df)
```

I have included an 'expected distance' column so we can later do some unit tests

We can convert this into a tidy format as follows:

```{r}
df_c <- df %>% filter(id == "centroid")
df_p <- df %>% filter(id != "centroid")

suffixes = c(point="_p", centroid="_c")

df_d <- dplyr::left_join(df_p, df_c, by="cluster", suffix = suffixes) %>% 
  dplyr::select(-expected_distance_c, -cluster, -id_p, -id_c) %>% 
  dplyr::select(-dplyr::one_of("expected_distance_p"), dplyr::one_of("expected_distance_p")) %>% 
  dplyr::rename(expected_distance =expected_distance_p)
  
knitr::kable(df_d)
```

To compute a distance, we want pairs of vectors to put in a distance function like distance(v1, v2)

```{r}
cols_to_vector <- function(c1,c2) {
  purrr::map2(c1,c2, function(a,b) {c(a,b)})
}

df_d <- df_d %>%
  dplyr::mutate(v_p = cols_to_vector(x_p, y_p)) %>%
  dplyr::mutate(v_c = cols_to_vector(x_c, y_c)) 

kable(df_d)
```

Apply our distance function:

```{r}

get_dist <- function(v1, v2) {
    as.double(dist(rbind(v1, v2)))
  }

df_d <- df_d %>% 
  mutate(distance = purrr::map2_dbl(v_p, v_c, get_dist))

kable(df_d)
```

Check that it gives the right result:

```{r}
testthat::expect_true(all.equal(df_d$expected_distance, df_d$distance))
```



